apiVersion: v1
kind: Pod
metadata:
  name: extraresources
spec:
   containers: 
     - name: container-with-limits
       image: nginx
       ports:
          - containerPort: 80
            protocal: TCP 
       resources:
          limits:
            memory: "128G"    
            cpu: "64"
          requests:
            memory: "64G"       
            cpu: "32"