---
apiVersion: v1
kind: Pod
metadata:
  name: labels
  labels:
     environment: developer
     team: prod
     project: ecom
spec:
   containers: 
     - name: web
       image: nginx
       ports:
            containerPort: 80
            protocal: TCP     