---
apiVersion: v1
kind: Pod
metadata:
  name: hello-world
  labels:
     app: hello-world
spec:
   containers: 
     - name: web
       image: httpd
       ports:
          - name: web
            containerPort: 80
            protocal: TCP     