---
apiVersion: v1
kind: ReplicaSet
metadata: 
  name: httpd
  labels:
     app: httpd
spec:
  minReadySeconds: 5
  replicas: 2
  selector:
     matchLabels:
      app: httpd
  template:
     metadata:
       labels:     
        app: httpd
     spec:   
      containers:
        - name: http-container
          image: httpd:latest
          ports:
            - containerPort: 80
              protocol: TCP
         livenessProbe:
           httpGet:
            port: 80
            path: /
         readinessProbe:
           httpGet:
            port: 80
            path: /
           initialDelaySeconds: 1
           periodSeconds: 5 
